#!/bin/sh
#
# Release gate items 19 and 20: the specification index and status audit.
#
# GENERATED, NOT WRITTEN. An index maintained by hand is a list of the documents
# someone remembered, and it goes stale the first time one is added. This walks
# the filesystem, so a specification that exists is a specification that appears.
#
#   ./build-spec-index.sh            write SPECIFICATION_INDEX.md
#   ./build-spec-index.sh --check    fail if the committed index is out of date
#
# The --check mode is what makes this a gate rather than a convenience: it is
# run by local-gates.sh, so adding a specification without regenerating the
# index fails the build.

set -e

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
INDEX="$ROOT/mcl-core/SPECIFICATION_INDEX.md"
WORK=${TMPDIR:-/tmp}/mcl-spec-index
OUT="$WORK/index.md"

CHECK=0
if [ "$1" = "--check" ]; then
    CHECK=1
fi

rm -rf "$WORK"
mkdir -p "$WORK"

# A status line may be "Status: X" or "**Status:** X", at the start of a line or
# after markdown emphasis. Anchoring to the line start alone missed six
# documents on the first attempt -- the ones using the bold form.
extract_status() {
    grep -m1 -iE '^\**status:?\**' "$1" 2>/dev/null \
        | sed -E 's/^\**[Ss]tatus:?\**[[:space:]]*//' \
        | sed 's/\*\*//g' \
        | cut -c1-70
}

{
    echo "# MCL specification index"
    echo
    echo "**Generated by \`mcl-core/tools/build-spec-index.sh\`. Do not edit by"
    echo "hand.** An index maintained by hand lists the documents someone"
    echo "remembered; this one walks the filesystem, and \`--check\` fails the"
    echo "build if it is out of date."
    echo
    echo "## What the statuses mean"
    echo
    echo "| Status | Meaning |"
    echo "|---|---|"
    echo "| **Stable** | Frozen. Bytes and meanings do not change without a new major version. |"
    echo "| **Candidate** | Complete and normative, awaiting the independent interoperability that promotion requires. |"
    echo "| **Research Draft** | Not normative. May change without notice. Not a basis for an implementation. |"
    echo "| **Superseded** | Retained as a record. Never deleted, never edited to look current. |"
    echo
    echo "**No document in MCL is Stable yet.** Stable requires the go/no-go"
    echo "rule in \`governance/V1_SCOPE.md\` §6, which requires independent"
    echo "interoperability evidence for the exact bytes being frozen."
    echo

    for repo in mcl-core mcl-wire mcl-link mcl-sdk mcl-ap mcl-ip mcl-ble mcl-uwb; do
        [ -d "$ROOT/$repo/spec" ] || continue
        any=$(find "$ROOT/$repo/spec" -maxdepth 1 -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
        [ "$any" = "0" ] && continue

        echo "## $repo"
        echo
        echo "| Document | Status |"
        echo "|---|---|"
        for spec in "$ROOT/$repo"/spec/*.md; do
            [ -e "$spec" ] || continue
            base=$(basename "$spec")
            status=$(extract_status "$spec")
            [ -z "$status" ] && status="**NO STATUS LINE**"
            echo "| [\`$base\`](../$repo/spec/$base) | $status |"
        done
        echo
    done

    echo "## Governance and conformance documents"
    echo
    echo "| Document | Purpose |"
    echo "|---|---|"
    echo "| [\`governance/V1_SCOPE.md\`](governance/V1_SCOPE.md) | What v1.0 claims. The authority for every disposition. |"
    echo "| [\`governance/RELEASE_GATE_V1.md\`](governance/RELEASE_GATE_V1.md) | The 34 rows that must close before a tag exists. |"
    echo "| [\`governance/GOVERNANCE.md\`](governance/GOVERNANCE.md) | How the project operates today, and what it cannot do. |"
    echo "| [\`governance/ARCHITECTURE_CHARTER.md\`](governance/ARCHITECTURE_CHARTER.md) | The invariants no layer may violate. |"
    echo "| [\`governance/REGISTRY_POLICY.md\`](governance/REGISTRY_POLICY.md) | Allocation policy shared by every registry. |"
    echo "| [\`governance/MACHINE_CLASS_AUDIT.md\`](governance/MACHINE_CLASS_AUDIT.md) | Why \`machine_class\` left the Stable body. |"
    echo "| [\`SECURITY.md\`](SECURITY.md) | What v1.0 does not protect against, and how to report what it does. |"
    echo "| [\`conformance/independent/SPEC_GAPS.md\`](conformance/independent/SPEC_GAPS.md) | What a clean-room implementer had to work out. |"
    echo "| [\`conformance/api-baseline-v1.txt\`](conformance/api-baseline-v1.txt) | The public symbol surface. |"
    echo

    echo "## Compatibility matrix"
    echo
    echo "Exactly what constitutes MCL v1.0. **This table is the answer to"
    echo "\"which version of what\".**"
    echo
    echo "| Component | v1.0 |"
    echo "|---|---|"
    echo "| Wire major | 1 — defined, **not yet cut**; the codec still refuses it |"
    echo "| Wire experimental major | 0 — permanent, never changes |"
    echo "| Link major | 1 — defined, not yet cut |"
    echo "| Stable semantic objects | \`PRESENCE\`, \`TRANSPORT_OFFER\`, \`TRANSPORT_ACCEPT\` |"
    echo "| Candidate semantic objects | \`HAZARD\`, \`REQUEST\`, \`AUTHORITY_CLAIM\`, \`DEGRADED_STATE\` — carried at major 0 only |"
    echo "| Stable Link frame classes | 9 of 10; \`ADAPT\` reserved |"
    echo "| Stable transports | IP (\`transport_id\` 2), BLE (3) |"
    echo "| Stable transport profiles | **none assigned yet** — both specifications are Candidate; profile 192 is Experimental Use in each and is never relabelled |"
    echo "| Experimental transports | AP (1), UWB (4) |"
    echo "| Stable extension IDs | **none** — the mechanism ships, the table is empty by design |"
    echo "| Negotiated feature bits | **none assigned** — same disposition |"
    echo "| API compatibility | source/API, **not** binary ABI |"
    echo "| Cryptography | none. See \`SECURITY.md\` |"
    echo
    echo "Generated from the repository tree. Regenerate with"
    echo "\`mcl-core/tools/build-spec-index.sh\`."
} > "$OUT"

if [ "$CHECK" -eq 1 ]; then
    if [ ! -f "$INDEX" ]; then
        echo "no specification index at $INDEX"
        exit 1
    fi
    if diff -q "$INDEX" "$OUT" > /dev/null 2>&1; then
        specs=$(grep -c '^| \[`' "$OUT" || true)
        echo "specification index is current ($specs rows)"
        exit 0
    fi
    echo "SPECIFICATION INDEX IS OUT OF DATE"
    echo
    diff "$INDEX" "$OUT" | head -40
    echo
    echo "Regenerate with: mcl-core/tools/build-spec-index.sh"
    exit 1
fi

cp "$OUT" "$INDEX"
echo "wrote $INDEX"
grep -c '^| \[`' "$INDEX" | sed 's/^/rows: /'

# A specification with no status line is a real defect: a reader cannot tell
# whether it may be implemented. Reported here rather than silently indexed.
if grep -q 'NO STATUS LINE' "$INDEX"; then
    echo
    echo "WARNING: some specifications carry no status line:"
    grep 'NO STATUS LINE' "$INDEX"
    exit 1
fi
