#!/bin/sh
#
# Release gate items 19 and 20: the specification index and status audit.
#
# GENERATED, NOT WRITTEN. An index maintained by hand is a list of the documents
# someone remembered, and it goes stale the first time one is added. This walks
# the filesystem, so a specification that exists is a specification that appears.
#
#   ./build-spec-index.sh            write SPECIFICATION_INDEX.md
#   ./build-spec-index.sh --check    fail if the committed index is out of date
#
# The --check mode is what makes this a gate rather than a convenience: it is
# run by local-gates.sh, so adding a specification without regenerating the
# index fails the build.

set -e

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
INDEX="$ROOT/mcl-core/SPECIFICATION_INDEX.md"
WORK=${TMPDIR:-/tmp}/mcl-spec-index
OUT="$WORK/index.md"

CHECK=0
if [ "$1" = "--check" ]; then
    CHECK=1
fi

rm -rf "$WORK"
mkdir -p "$WORK"

# A status line may be "Status: X" or "**Status:** X", at the start of a line or
# after markdown emphasis. Anchoring to the line start alone missed six
# documents on the first attempt -- the ones using the bold form.
#
# The carriage return is stripped explicitly. Several specifications are stored
# with CRLF endings, and a grep that keeps the CR carries it into the generated
# table -- which puts a stray control character in a published document and
# makes --check depend on how the reader's git happened to configure line
# endings. A gate that passes or fails on a checkout setting is not a gate, and
# the committed index did carry five of those characters until this was added.
extract_status() {
    grep -m1 -iE '^\**status:?\**' "$1" 2>/dev/null \
        | tr -d '\r' \
        | sed -E 's/^\**[Ss]tatus:?\**[[:space:]]*//' \
        | sed 's/\*\*//g' \
        | cut -c1-70
}

# The transport rows of the compatibility matrix are read from the registry
# that governs them, for the same reason. Hardcoded here, they said transports
# 2 and 3 were Stable while mcl-link/registries/transport-ids-v0.1.json still
# marked all four provisional -- and the registry is the authoritative source,
# so the matrix was simply wrong. A generated document must not be able to
# contradict the file it is generated from.
TRANSPORT_REGISTRY="$ROOT/mcl-link/registries/transport-ids-v0.1.json"
transports_with_status() {
    tr -d ' \n' < "$TRANSPORT_REGISTRY" \
        | sed 's/},{/}\n{/g' \
        | grep '"owner_repo"' \
        | grep "\"status\":\"$1\"" \
        | sed -E 's/.*"id":([0-9]+).*"name":"([^"]*)".*/\2 (\1)/' \
        | paste -sd ',' - \
        | sed 's/,/, /g'
}
STABLE_TRANSPORTS=$(transports_with_status stable)
PROVISIONAL_TRANSPORTS=$(transports_with_status provisional)
[ -n "$STABLE_TRANSPORTS" ] || STABLE_TRANSPORTS="**none**"
[ -n "$PROVISIONAL_TRANSPORTS" ] || PROVISIONAL_TRANSPORTS="**none**"

# Collect the Stable documents by reading their own status lines, so the
# summary above the table and the table itself cannot disagree.
STABLE_SPECS=""
for repo in mcl-core mcl-wire mcl-link mcl-sdk mcl-ap mcl-ip mcl-ble mcl-uwb; do
    [ -d "$ROOT/$repo/spec" ] || continue
    for spec in "$ROOT/$repo"/spec/*.md; do
        [ -e "$spec" ] || continue
        case "$(extract_status "$spec")" in
            Stable*|stable*|STABLE*)
                STABLE_SPECS="$STABLE_SPECS $repo/spec/$(basename "$spec")"
                ;;
        esac
    done
done

{
    echo "# MCL specification index"
    echo
    echo "**Generated by \`mcl-core/tools/build-spec-index.sh\`. Do not edit by"
    echo "hand.** An index maintained by hand lists the documents someone"
    echo "remembered; this one walks the filesystem, and \`--check\` fails the"
    echo "build if it is out of date."
    echo
    echo "## What the statuses mean"
    echo
    echo "| Status | Meaning |"
    echo "|---|---|"
    echo "| **Stable** | Frozen. Bytes and meanings do not change without a new major version. |"
    echo "| **Candidate** | Complete and normative, awaiting the independent interoperability that promotion requires. |"
    echo "| **Research Draft** | Not normative. May change without notice. Not a basis for an implementation. |"
    echo "| **Superseded** | Retained as a record. Never deleted, never edited to look current. |"
    echo
    # Which documents are Stable is READ FROM THE TREE, never asserted here.
    # This sentence used to be the hardcoded claim "No document in MCL is
    # Stable yet". It stayed in the file after the two profile specifications
    # were promoted on 2026-09-04, so a generated index contradicted its own
    # status column. A generator that walks the filesystem for the rows and
    # hardcodes the summary has no business being trusted for either.
    if [ -n "$STABLE_SPECS" ]; then
        echo "**Stable documents, read from the tree at generation time:**"
        echo
        for s in $STABLE_SPECS; do
            echo "- \`$s\`"
        done
        echo
        echo "Every other document is below Stable. Promotion requires the"
        echo "go/no-go rule in \`governance/V1_SCOPE.md\` §6 — independent"
        echo "interoperability evidence for the exact bytes being frozen — and"
        echo "the \`governance/REGISTRY_POLICY.md\` §2 requirements for any"
        echo "registry value the document assigns."
    else
        echo "**No document in MCL is Stable.** Stable requires the go/no-go"
        echo "rule in \`governance/V1_SCOPE.md\` §6, which requires independent"
        echo "interoperability evidence for the exact bytes being frozen."
    fi
    echo

    for repo in mcl-core mcl-wire mcl-link mcl-sdk mcl-ap mcl-ip mcl-ble mcl-uwb; do
        [ -d "$ROOT/$repo/spec" ] || continue
        any=$(find "$ROOT/$repo/spec" -maxdepth 1 -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
        [ "$any" = "0" ] && continue

        echo "## $repo"
        echo
        echo "| Document | Status |"
        echo "|---|---|"
        for spec in "$ROOT/$repo"/spec/*.md; do
            [ -e "$spec" ] || continue
            base=$(basename "$spec")
            status=$(extract_status "$spec")
            [ -z "$status" ] && status="**NO STATUS LINE**"
            echo "| [\`$base\`](../$repo/spec/$base) | $status |"
        done
        echo
    done

    echo "## Governance and conformance documents"
    echo
    echo "| Document | Purpose |"
    echo "|---|---|"
    echo "| [\`governance/V1_SCOPE.md\`](governance/V1_SCOPE.md) | What v1.0 claims. The authority for every disposition. |"
    echo "| [\`governance/RELEASE_GATE_V1.md\`](governance/RELEASE_GATE_V1.md) | The 34 rows that must close before a tag exists. |"
    echo "| [\`governance/GOVERNANCE.md\`](governance/GOVERNANCE.md) | How the project operates today, and what it cannot do. |"
    echo "| [\`governance/ARCHITECTURE_CHARTER.md\`](governance/ARCHITECTURE_CHARTER.md) | The invariants no layer may violate. |"
    echo "| [\`governance/REGISTRY_POLICY.md\`](governance/REGISTRY_POLICY.md) | Allocation policy shared by every registry. |"
    echo "| [\`governance/MACHINE_CLASS_AUDIT.md\`](governance/MACHINE_CLASS_AUDIT.md) | Why \`machine_class\` left the Stable body. |"
    echo "| [\`SECURITY.md\`](SECURITY.md) | What v1.0 does not protect against, and how to report what it does. |"
    echo "| [\`conformance/independent/SPEC_GAPS.md\`](conformance/independent/SPEC_GAPS.md) | What a clean-room implementer had to work out. |"
    echo "| [\`conformance/api-baseline-v1.txt\`](conformance/api-baseline-v1.txt) | The public symbol surface. |"
    echo

    echo "## Compatibility matrix"
    echo
    echo "Exactly what constitutes MCL v1.0. **This table is the answer to"
    echo "\"which version of what\".**"
    echo
    echo "| Component | v1.0 |"
    echo "|---|---|"
    echo "| Wire major | 1 — **cut**; encoded, decoded, and frozen by the immutable major-1 vectors |"
    echo "| Wire experimental major | 0 — permanent, never changes |"
    echo "| Link major | 1 — **cut**; frame layout byte-identical to major 0, class dispositions frozen |"
    echo "| Default major emitted | 0 — v1.0 promises source compatibility, so the pre-cut encode calls emit what they always emitted; the \`_at_major\` calls select 1 |"
    echo "| Stable semantic objects | \`PRESENCE\`, \`TRANSPORT_OFFER\`, \`TRANSPORT_ACCEPT\` |"
    echo "| Candidate semantic objects | \`HAZARD\`, \`REQUEST\`, \`AUTHORITY_CLAIM\`, \`DEGRADED_STATE\` — carried at major 0 only |"
    echo "| Stable Link frame classes | 9 of 10; \`ADAPT\` reserved |"
    echo "| Stable transports | $STABLE_TRANSPORTS |"
    echo "| Stable transport profiles | **IP-DATAGRAM = 1** and **BLE-GATT = 1**, MCL Standards Action, 2026-09-04. Both specifications are Stable. Profile 192 remains Experimental Use in each and was never relabelled |"
    echo "| Provisional transports | $PROVISIONAL_TRANSPORTS — assigned for use, not frozen |"
    echo "| Stable extension IDs | **none** — the mechanism ships, the table is empty by design |"
    echo "| Negotiated feature bits | **none assigned** — same disposition |"
    echo "| API compatibility | source/API, **not** binary ABI |"
    echo "| Cryptography | none. See \`SECURITY.md\` |"
    echo
    echo "Generated from the repository tree. Regenerate with"
    echo "\`mcl-core/tools/build-spec-index.sh\`."
} > "$OUT"

if [ "$CHECK" -eq 1 ]; then
    if [ ! -f "$INDEX" ]; then
        echo "no specification index at $INDEX"
        exit 1
    fi
    if diff -q "$INDEX" "$OUT" > /dev/null 2>&1; then
        specs=$(grep -c '^| \[`' "$OUT" || true)
        echo "specification index is current ($specs rows)"
        exit 0
    fi
    echo "SPECIFICATION INDEX IS OUT OF DATE"
    echo
    diff "$INDEX" "$OUT" | head -40
    echo
    echo "Regenerate with: mcl-core/tools/build-spec-index.sh"
    exit 1
fi

cp "$OUT" "$INDEX"
echo "wrote $INDEX"
grep -c '^| \[`' "$INDEX" | sed 's/^/rows: /'

# A specification with no status line is a real defect: a reader cannot tell
# whether it may be implemented. Reported here rather than silently indexed.
if grep -q 'NO STATUS LINE' "$INDEX"; then
    echo
    echo "WARNING: some specifications carry no status line:"
    grep 'NO STATUS LINE' "$INDEX"
    exit 1
fi
